# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: blog
services:
  cassandra:
    image: cassandra:5.0
    container_name: blog-cassandra
    # volumes:
    #   - ~/volumes/jhipster/blog/cassandra/:/var/lib/cassandra/data
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:7200:7000
      - 127.0.0.1:7201:7001
      - 127.0.0.1:7399:7199
      - 127.0.0.1:9242:9042
      - 127.0.0.1:9360:9160
    healthcheck:
      test: ['CMD', 'cqlsh', '-e', 'describe keyspaces']
      interval: 5s
      timeout: 25s
      retries: 20
    labels:
      org.springframework.boot.ignore: true
  cassandra-migration:
    environment:
      - CASSANDRA_CONTACT_POINT=blog-cassandra
      - USER=docker-cassandra-migration
      # - DEBUG_LOG=1 # uncomment to show debug logs during the migration process
      - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
    build:
      context: .
      dockerfile: cassandra/Cassandra-Migration.Dockerfile
    volumes:
      - ../resources/config/cql:/cql:ro
    labels:
      org.springframework.boot.ignore: true
