# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZTZiN2IwNTBkNzMxZWI2MDFhNGQ2ZDA3YTc3YTA0NTE1Yjg2NmEyNzRkYTQ3OGZiZThlN2U4MTI3Njg3YTAzZjc3MWQzNjgzNzJiOGY1YTE3MTBlYTQ3NDg0MDQ5YTQyZDNlZTBiNGI2YjU2MGM1MzkwYjQyMGQ4OTliMTE3YzU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
