#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: MjgxOWRiMDA1ZWE3ZDUwZDQyMGFlNWY2MDk4NzA3OGU4ODUzZjhjZWIzZTE4OTkyYTMxOTYxZDhkYzFhYTM3ZDA0MjQ2MWNhNzRmMDM1MjVkZGJmNjgxNjdjZWI3MTU5ZmIxNw==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
