#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZThiZDg5YTMyYjNjYjk2ODVkYjA1ZTY0ZGU0ODk3YzgzYjc0NDQ5NGEwNTQ1OGY3YTJiYTNmMTZhZmYzODNiZDhjNWRlYjJjZTk0YzYwMTUyMjgyY2Y0MmM4ODYwNzEwNGI1Ng==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
