#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NzMwYTdmNjYzZGE0OTU5N2UyN2QxN2JmYjRmOTA3ZWZiYWFhZWUxZGNlZjIxNTY0OGU4MjRiZTI1M2I3MzhhOWJkODExYjM0OGU3MzVlZmUzZWFiY2FmMzQ3MzAyY2RiYzEyNw==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
