#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: MDNkZGZhMjY0Mzk2Njg5YmI4MmNmN2RkZDk2M2JkNGExZWQxYzZlYTc2ZGI5OWI1N2JiYTYyYzczYTUyZjVhZjhjZGRmNGQ4YzM3YTUxMTcxZmRlZWY4OGUwNjliMWM3Y2E2ZA==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
