# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MmRiMGM3NjA1MDE3MGM5OTM0YTc3Yzk1MmUzMTYzZWQ3MDI0MmM4MGZlNTg0ZGJhNWU0MTIzOTAxODdiOTlhMGQzMDE4ZGQyOTc4MTljNzE4MDFkMTllOTUzNmIwMzFlZDlmY2E1NDliZGUxZmViZjQyMWVhNjg1Yjc0NTlmMWU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
